-- Database used: MySQL.
-- 'sickest' floor means the floor with the most cases.
SELECT EMP_FLOOR as sickest_floor FROM CASES JOIN EMPLOYEE ON CASES.EMP_ID = EMPLOYEE.EMP_ID GROUP BY EMP_FLOOR
HAVING COUNT(*) = (
	SELECT MAX(COUNT) FROM(
		SELECT EMP_FLOOR, COUNT(*)AS COUNT FROM CASES JOIN EMPLOYEE ON CASES.EMP_ID = EMPLOYEE.EMP_ID GROUP BY EMP_FLOOR) AS COUNT);